### ISSUE TITLE
转换出错吗？

### ISSUE THREAD

**Issue by yeluoqiuzhi** [qdsang/ttf2svg#6]
既然你也说中文，我就不秀逗我的英语了。我用你的fonts-streamline和ttf2svg写了个小功能，就是调整了一下使用方式。可是我转换之后的字体都是向后一位的，例如你提取我的1,实际提取了2,而2则提取了3,如果不用这个ttf2svg就没问题。请问这是bug吗

**Comment by qdsang** [comment]
有这坑？ 提供下你的测试demo

**Comment by yeluoqiuzhi** [comment]
demo已经不见了。。。。但有个东西.我把你的代码修改一下搬到这里来了……https://github.com/yeluoqiuzhi/font-cutter，我们用font-spider，字体经常会出现字体轮廓偏细模糊大小不一，很难看，所以用你这个。我就想着你也有ttf2svg就用你的来转了，可是用你的转就出现上面的问题。所以我用其它的软件手动转，没问题的

**Comment by qdsang** [comment]
牛逼，排斥 ttf2svg bug的事儿就交给你了

**Comment by yeluoqiuzhi** [comment]
别啊，我是小白一个。不过我觉得没太大必要，如果你没空。我用别的转成svg,照样可以用
