### ISSUE TITLE
Output path is wrong

### ISSUE THREAD

**Issue by julianxhokaxhiu** [qdsang/ttf2svg#7]
Hi,

can I ask you why [did you hardcode the output path](https://github.com/qdsang/ttf2svg/blob/master/bin/ttf2svg.js#L15)? Can you please fix it to accept a third argument?

Thanks in advance!

**Comment by julianxhokaxhiu** [comment]
Any update on this?

**Comment by qdsang** [comment]
Sorry, I forgot.

**Comment by qdsang** [comment]
@julianxhokaxhiu fix ok.

**Comment by julianxhokaxhiu** [comment]
Thanks! Was the fix published on NPM?

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
